version: "3.9"

services:
  web:
    build: 
      context: ./backend
      dockerfile: Dockerfile
    container_name: web
    ports:
      - "8000:8000"
    environment:
      # These can also be moved to an .env file if you prefer
      POSTGRES_DB: "postgres"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
      POSTGRES_HOST: "db"
      POSTGRES_PORT: "5432"

    depends_on:
      - db
      
  db:
    image: postgres:15
    restart: always
    container_name: db
    environment:
      POSTGRES_DB: "postgres"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"

  frontendnuxt:
    build: 
      context: ./frontend
      dockerfile: Dockerfile
    container_name: frontendnuxt
    ports:
      - "3000:3000"
    depends_on:
      - web
