apiVersion: apps/v1
kind: Deployment
metadata:
  name: nuxt
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nuxt
  template:
    metadata:
      labels:
        app: nuxt
    spec:
      containers:
      - name: nuxt
        image: ghcr.io/crunchytoaster/crunchytoaster-nuxt:latest
        env:
        - name: API_URL
          value: "http://django:8000"
        ports:
        - containerPort: 3000