apiVersion: v1
kind: Service
metadata:
  name: postgres
  namespace: staging
spec:
  clusterIP: None        # headless service for StatefulSet
  selector:
    app: postgres
  ports:
  - port: 5432
    targetPort: 5432
