apiVersion: apps/v1
kind: Deployment
metadata:
  name: web
  namespace: staging
spec:
  replicas: 2
  selector:
    matchLabels:
      app: web
  template:
    metadata:
      labels:
        app: web
    spec:
      containers:
      - name: django
        image: ghcr.io/crunchytoaster/crunchytoaster-web:005e6b86
        ports:
        - containerPort: 8000
        env:
        - name: POSTGRES_HOST
          value: postgres.staging.svc.cluster.local
        - name: POSTGRES_DB
          valueFrom:
            secretKeyRef:
              name: pg-creds
              key: POSTGRES_DB
        - name: POSTGRES_USER
          valueFrom:
            secretKeyRef:
              name: pg-creds
              key: POSTGRES_USER
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: pg-creds
              key: POSTGRES_PASSWORD
