name: Build & Publish images

on:
  push:
    branches: [main, staging]

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      id-token: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Setup Docker buildx
        uses: docker/setup-buildx-action@v3
      
      - name: Setup Quemu
        uses: docker/setup-qemu-action@v3
      
      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set image tag
        run: echo "TAG=$(echo ${{ github.sha }} | cut -c1-8)" >> $GITHUB_ENV

      - name: Build & push Django backend
        uses: docker/build-push-action@v4
        with:
          context: ./backend
          push: true
          tags: |
            ghcr.io/crunchytoaster/crunchytoaster-web:${{ env.TAG }}

      - name: Build & push Nuxt frontend
        uses: docker/build-push-action@v4
        with:
          context: ./frontend
          push: true
          tags: |
            ghcr.io/crunchytoaster/crunchytoaster-nuxt:${{ env.TAG }}

      - name: Install kubectl
        uses: azure/setup-kubectl@v3
        with:
          version: 'v1.27.3'

      - name: Configure Kubeconfig
        run: |
          echo "${{ secrets.KUBE_CONFIG_DATA }}" | base64 --decode > $HOME/.kube/config

      - name: Update web Deployment
        run: |
          kubectl set image deployment/web \
            django=ghcr.io/crunchytoaster/crunchytoaster-web:${{ env.TAG }} \
            -n staging
          kubectl rollout status deployment/web -n staging

      - name: Update nuxt Deployment
        run: |
          kubectl set image deployment/nuxt \
            nuxt=ghcr.io/crunchytoaster/crunchytoaster-nuxt:${{ env.TAG }} \
            -n staging
          kubectl rollout status deployment/nuxt -n staging